const { execSync } = require('child_process')
const { readFileSync } = require('fs')

console.log('Checking for Uncommitted Changes...')
execSync('git diff-index --quiet HEAD --')
console.log('Testing...')
execSync('npm test')
console.log('Updating Version...')
execSync('mkdir -p scratch')
execSync('npx stampver -i patch -u')
console.log('Building...')
execSync('npm run build')
console.log('Committing Version Changes...')
execSync(`git add :/`)
console.log('Tagging...')
const tagName = readFileSync('scratch/version.tag.txt')
const tagDescription = readFileSync('scratch/version.desc.txt')
execSync(`git tag -a ${tagName} -m '${tagDescription}'`)
execSync(`git commit -m '${tagDescription}'`)
console.log('Pushing...')
execSync('git push --follow-tags')
console.log('Publishing...')
execSync('npm publish')
